### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by xrizonx** [JakubDotPy/logitycoon_automation#3]
HI,

Thanks for making this tool but for some reason even after installing requirements i cannot fix this error:

INFO     - initializing game with WebInterface
INFO     - ==================================== START =====================================
INFO     - ================================== AUTOMATION ==================================
WARNING  - experimental - use at own risk
INFO     - ===================================  1. trip ===================================
INFO     - ===================================== END ======================================
Traceback (most recent call last):
  File "F:\Plex\logitycoon_automation-master\logitycoon_automation-master\main.py", line 83, in <module>
    raise SystemExit(main())
                     ^^^^^^
  File "F:\Plex\logitycoon_automation-master\logitycoon_automation-master\main.py", line 77, in main
    g.play()
  File "F:\Plex\logitycoon_automation-master\logitycoon_automation-master\main.py", line 43, in play
    best_trip_id = fm.get_trip_id()
                   ^^^^^^^^^^^^^^^^
  File "F:\Plex\logitycoon_automation-master\logitycoon_automation-master\company\managers.py", line 27, in get_trip_id
    return self.interface.get_trip_id()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\Plex\logitycoon_automation-master\logitycoon_automation-master\interfaces\web.py", line 55, in get_trip_id
    return int(row[0].attrs['value'])
               ~~~^^^
IndexError: list index out of range

Any advice?

**Comment by xrizonx** [comment]
Managed to get this to work. Issue i face now it only departs 1 of my 4 trucks any plans to have it handle multiple trips?
